export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const REDIRECT_ROUTE = '/redirect'
export const DEVICE_ROUTE = '/device'
